//! sqlx/PostgreSQL error → `DbError` conversion for user statements.

use sqlx::postgres::{PgDatabaseError, PgErrorPosition};

use crate::core::error::{DbError, ErrorPosition};

/// SQLSTATE `active_sql_transaction`: the statement refuses to run inside a
/// transaction block (`VACUUM`, `CREATE DATABASE`, ...).
const ACTIVE_SQL_TRANSACTION: &str = "25001";

/// Convert an error raised by anything other than the user's statement
/// (acquiring a connection, `BEGIN`, `COMMIT`, `SET search_path`).
pub(super) fn plain_error(err: &sqlx::Error) -> DbError {
    DbError::QueryFailed(err.to_string())
}

/// Convert an error raised while preparing or running the user's statement.
///
/// The server's `detail` and `hint` are appended to the message, and the
/// reported cursor position — a 1-based character index into `sql` — becomes
/// the error's line/column.
pub(super) fn statement_error(err: &sqlx::Error, sql: &str) -> DbError {
    let Some(pg) = pg_error(err) else {
        return plain_error(err);
    };
    let message = compose_message(&err.to_string(), pg.detail(), pg.hint());
    let position = match pg.position() {
        Some(PgErrorPosition::Original(index)) => position_at(sql, index),
        // A position inside a query generated by a function body says nothing
        // about where the failure is in the text the user submitted.
        Some(PgErrorPosition::Internal { .. }) | None => None,
    };
    DbError::query_failed(message, position)
}

/// Whether the server refused the statement because a transaction is open.
pub(super) fn is_transaction_block_refusal(err: &sqlx::Error) -> bool {
    pg_error(err).is_some_and(|pg| pg.code() == ACTIVE_SQL_TRANSACTION)
}

fn pg_error(err: &sqlx::Error) -> Option<&PgDatabaseError> {
    err.as_database_error()?
        .try_downcast_ref::<PgDatabaseError>()
}

/// Append the optional `DETAIL` / `HINT` lines the way psql prints them.
fn compose_message(base: &str, detail: Option<&str>, hint: Option<&str>) -> String {
    let mut message = base.to_string();
    for (label, text) in [("DETAIL", detail), ("HINT", hint)] {
        if let Some(text) = text.map(str::trim).filter(|t| !t.is_empty()) {
            message.push_str(&format!("\n{label}: {text}"));
        }
    }
    message
}

/// Translate the server's 1-based character index into a line/column.
/// An index of 0 is not a position PostgreSQL ever reports.
fn position_at(sql: &str, index: usize) -> Option<ErrorPosition> {
    let offset = index.checked_sub(1)?;
    Some(ErrorPosition::from_char_offset(sql, offset))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn message_without_extras_is_unchanged() {
        assert_eq!(compose_message("boom", None, None), "boom");
        assert_eq!(compose_message("boom", Some("  "), Some("")), "boom");
    }

    #[test]
    fn detail_and_hint_are_appended_in_order() {
        assert_eq!(
            compose_message(
                "duplicate key",
                Some("Key (id)=(1) already exists."),
                Some("Use ON CONFLICT.")
            ),
            "duplicate key\nDETAIL: Key (id)=(1) already exists.\nHINT: Use ON CONFLICT."
        );
        assert_eq!(
            compose_message("no column", None, Some("Perhaps you meant \"name\".")),
            "no column\nHINT: Perhaps you meant \"name\"."
        );
    }

    #[test]
    fn position_is_one_based_in_characters() {
        let sql = "SELECT 1\nFROM nope";
        // Character 15 is the `n` of `nope`.
        assert_eq!(
            position_at(sql, 15),
            Some(ErrorPosition {
                line: 2,
                col: Some(6)
            })
        );
        assert_eq!(
            position_at(sql, 1),
            Some(ErrorPosition {
                line: 1,
                col: Some(1)
            })
        );
    }

    #[test]
    fn position_counts_characters_not_bytes() {
        let sql = "SELECT 'ñé' FROM nope";
        assert_eq!(
            position_at(sql, 18),
            Some(ErrorPosition {
                line: 1,
                col: Some(18)
            })
        );
    }

    #[test]
    fn zero_is_not_a_position() {
        assert_eq!(position_at("SELECT 1", 0), None);
    }

    #[test]
    fn non_database_errors_carry_no_position() {
        let err = statement_error(&sqlx::Error::PoolTimedOut, "SELECT 1");
        assert_eq!(err.position(), None);
        assert!(!is_transaction_block_refusal(&sqlx::Error::PoolTimedOut));
    }
}
